name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  get_it: 4.0.0
  mockito: ^4.1.1
  injectable:
    # 1.0.3
    path: ../injectable
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: 1.10.0
  effective_dart: ^1.2.0
  injectable_generator:
    #  1.0.3
    path: ../injectable_generator
