name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  # flutter:
  # sdk: flutter
  get_it: 4.0.0
  mockito: ^4.1.1
  injectable:
    path: ../injectable
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  build_runner:
  injectable_generator:
    path: ../injectable_generator
