name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  injectable:
    path: ../injectable/
  cupertino_icons: ^0.1.3
  provider:
  kiwi:
  get_it:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  injectable_generator:
    path: ../injectable_generator

flutter:
  uses-material-design: true
