name: example
description: A simple command-line application.

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  get_it: 5.0.0

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: 1.10.3
  effective_dart: ^1.3.0
  injectable_generator:
    #  1.0.3
    path: ../../injectable_generator
