builders:
  injectable_builder:
    import: "package:injectable_generator/builder.dart"
    builder_factories: ["injectableBuilder"]
    build_extensions: { ".json": [".injectable.json"] }
    auto_apply: dependents
    runs_before: [":injector_builder"]
    build_to: cache
  injector_builder:
    import: "package:injectable_generator/builder.dart"
    builder_factories: ["injectableConfigBuilder"]
    build_extensions: { ".dart": [".iconfig.dart"] }
    auto_apply: dependents
    build_to: source
