builders:
  injectable_builder:
    import: "package:injectable_generator/builder.dart"
    builder_factories:
      - "injectableBuilder"
    build_extensions: { ".dart": [".injectable.json"] }
    auto_apply: dependents
    runs_before:
      - "injectable_generator|config_builder"
    build_to: cache

  config_builder:
    import: "package:injectable_generator/builder.dart"
    builder_factories:
      - "injectableConfigBuilder"
    build_extensions: { ".dart": [".config.dart"] }
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        outputs:
          lib/injector/injector:
